acc/urls.py
from django.conf.urls import url
from . import views

app_name='acc'

urlpatterns = [
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^signup/$', views.SignupView.as_view(), name='login'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    ]

dashboard/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name='dash'

urlpatterns = [
    path('', views.MatchView.as_view(), name='match'),
    path('ajax_user/<int:pk>/', views.UserInfoView.as_view(), name='ajax_user'),
    path('ajax_evidence/', views.EvidenceList.as_view(), name='ajax_evidence'),
    path('ajax_action', views.MatchAction.as_view(), name='ajax_action'),
    path('upload_evidence/<int:pk>/', views.UploadEvidence.as_view(), name='upload_evidence'),
    path('request_match', views.RequestMatch.as_view(), name='request_match'),
    path('profile', views.ProfileUpdateView.as_view(), name='profile'),
    path('matchadmin', views.MatchAdmin.as_view(), name='match_admin'),

    ]

mmm/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('acc.urls')),
    path('office/', include('dashboard.urls')),
    re_path(r'^media/(?P<path>.*)', serve, {'document_root': settings.MEDIA_ROOT}),
    path('',include('main.urls')),
]

dashboard/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from datetime import timedelta
# Create your models here.

class Plan(models.Model):
    name=models.CharField(max_length=200)
    amount=models.IntegerField(default=250)
    day_length=models.IntegerField()





class Investment(models.Model):
    day_started=models.DateTimeField(auto_now_add=True)

    plan=models.ForeignKey(Plan, on_delete=models.CASCADE)
    owner=models.ForeignKey(User, null=True, on_delete=models.CASCADE)
    maturity_date=models.DateTimeField(null=True)
    status=models.CharField(max_length=200, default='Maturing')
    completed_date=models.DateTimeField(null=True)

    def mature_inv(self):

        self.maturity_date=timezone.now()
        self.save()
        self.status = 'Matured'
        Payment.objects.bulk_create([Payment(investment=self),
                                     Payment(investment=self),
                                     Payment(investment=self)])

    def admin_mature_env(self):
        self.save()
        self.status = 'Matured'
        Payment.objects.bulk_create([Payment(investment=self,),
                                     Payment(investment=self),
                                     Payment(investment=self)])


class Payment(models.Model):
    investment=models.ForeignKey(Investment, on_delete=models.CASCADE)
    status=models.CharField(max_length=200, default='Awaiting Match')
    created_date=models.DateTimeField(auto_now_add=True, null=True)
    completion_date=models.DateTimeField(null=True)

    def match(self):
        #self.status='Awaiting Payment'
        self.save()



class Match(models.Model):
    payer=models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name='payer', blank=True)
    investment=models.ForeignKey(Investment, on_delete=models.CASCADE, related_name='investment', null=True, blank=True)
    plan=models.ForeignKey(Plan, on_delete=models.CASCADE, null=True, blank=True)
    receiver=models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name='receiver', blank=True)
    bitcoin_value=models.DecimalField(decimal_places=8,max_digits=70, null=True, blank=True)

    status=models.CharField(max_length=200,default='Waiting For Match', choices=(('Expired','Expired'),
                                                     ('Completed' , 'Completed'),
                                                     ('Waiting For Match','Waiting For Match'),
                                                     ('Waiting For Payment','Waiting For Payment')))
    time_matched=models.DateTimeField(null=True, blank=True)
    time_completed=models.DateTimeField(null=True, blank=True)
    expiry_date=models.DateTimeField(default=timezone.now(), null=True, blank=True)
    grace=models.BooleanField(default=True)
    created_date=models.DateTimeField(null=True, auto_now_add=True, blank=True)
    pay=models.ForeignKey(Payment, on_delete=models.CASCADE, null=True, blank=True)

    def complete_match(self,inv, pay):
        self.time_match=timezone.now()
        self.receiver=inv.owner
        self.bitcoin_value=get_bitcoin_value()
        self.status='Waiting For you to pay'
        self.expiry_date=timezone.now()+timedelta(days=1)
        self.pay=pay
        self.investment=inv
        self.save()



class Evidence(models.Model):
    proof = models.ImageField()
    for_match=models.ForeignKey(Match, on_delete=models.CASCADE)

def get_bitcoin_value():
    return 0.02

dashboard/forms.py
from django import forms
from django.contrib.auth.models import User
from acc.models import Profile



class UserForm(forms.ModelForm):
    class Meta:
        model=User
        fields=('username','first_name','last_name','email')

        widgets={
        'first_name':forms.TextInput(attrs={'class':'form-control borderprob'}),
        'last_name':forms.TextInput(attrs={'class':'form-control borderprob'}),
        'username':forms.TextInput(attrs={'class':'form-control borderprob'}),
        'email':forms.EmailInput(attrs={'class':'form-control borderprob'}),
        }

class ProfileForm(forms.ModelForm):
    class Meta:
        model=Profile
        fields=('picture','phone', 'bit_address')

        widgets={
        'bit_address':forms.TextInput(attrs={'class':'form-control'}),
        }

dashboard/views.py
from django.shortcuts import render
from django.template.loader import render_to_string
from django.views import View
from .models import Match, Evidence, Investment, Payment, get_bitcoin_value, Plan
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import DetailView, ListView
from django.contrib.auth.models import User
from django.http import JsonResponse, Http404, HttpResponseRedirect
from datetime import timedelta
from django.db.models import Q
from django.utils import timezone
from django.contrib import messages
from .forms import UserForm,ProfileForm
from acc.models import Profile

# Create your views here.

class MatchView(LoginRequiredMixin, View):
    template_name='remiel_admin/match.html'

    def get(self, request, *args, **kwargs):
       active_receive_matches=Match.objects.filter(receiver=request.user).exclude(status='Completed')
       old_receive_matches=Match.objects.filter(receiver=request.user).filter(status='Completed')[:10]
       active_pay_matches=Match.objects.filter(payer=request.user).exclude(status='Completed')
       old_pay_matches=Match.objects.filter(payer=request.user).filter(status='Completed')[:10]
       active_inv=Investment.objects.exclude(status='Complete').filter(owner=request.user)


       context={'arm':active_receive_matches, 'orm':old_receive_matches,
                'apm':active_pay_matches,'opm':old_pay_matches,
                'ainv':active_inv
                }
       return render(request, self.template_name, context)

class UserInfoView(LoginRequiredMixin, DetailView):
    model=User
    context_object_name = 'user'

    def get_context_data(self, **kwargs):
        context=super(UserInfoView, self).get_context_data(**kwargs)
        context['str_data']=render_to_string('remiel_admin/user_info.html', context)
        return context

    def render_to_response(self, context, **response_kwargs):
        return JsonResponse({'html_data': context['str_data']})



class EvidenceList(LoginRequiredMixin, ListView):
    model=Evidence
    match_id=None
    context_object_name = 'evidences'

    def get(self, request, *args, **kwargs):
        self.match_id=request.GET.get('match_id')
        return super(EvidenceList,self).get(request,*args, **kwargs)

    def get_queryset(self):
        try:
            match=Match.objects.get(pk=self.match_id)

        except Match.DoesNotExist:
            return Http404()
        return Evidence.objects.filter(for_match=match)


    def render_to_response(self, context, **response_kwargs):
        html_data=render_to_string('remiel_admin/evidences.html', context)

        return JsonResponse({'html_data': html_data})

class MatchAction(LoginRequiredMixin, View):

    def get(self, request, *args, **kwargs):
        action=request.GET.get('action')
        match_id=request.GET.get('match_id')
        try:
            match_obj=Match.objects.get(pk=match_id)
        except Match.DoesNotExist:
            return Http404()
        if action == 'Complete':
            match_obj.status='Completed'
            now=timezone.now()
            maturity_date = now+timedelta(days=7)
            inv = Investment(plan=match_obj.plan, status='Maturing',
                             owner=match_obj.payer,
                             maturity_date=maturity_date)
            match_obj.pay.status='Completed'
            match_obj.pay.save()
            related_inv=Payment.objects.exclude(status='Completed'
                                      ).filter(
                                           investment=match_obj.investment)
            if not related_inv.exists():
                match_obj.investment.status='Completed'
                match_obj.investment.save()

            inv.save()
            messages.success(request, "Payment Successful Approved")
        if action =='Extend':
            match_obj.expiry_date=match_obj.expiry_date+timedelta(hours=6)
            messages.success(request, "Payment deadline successfully extended")
            match_obj.grace=False



        match_obj.save()
        return JsonResponse({'status':True, 'redirect_url':'/office'})

class UploadEvidence(LoginRequiredMixin, View):

    def get(self, request, *args, **kwargs):

        pk=kwargs.pop('pk')
        context=dict()
        try:
            context['match']=Match.objects.get(pk=pk)
        except:
            return Http404()
        return render(request, 'remiel_admin/fileupload.html', context)

    def post(self, request,*args,**kwargs):

        

        pk = kwargs.pop('pk')
        try:
            match=Match.objects.get(pk=pk)
        except Match.DoesNotExist:
            return Http404()
        evidence= Evidence(for_match=match, proof=request.FILES['file'])
        evidence.save()

        return JsonResponse({'status':True})

class RequestMatch(LoginRequiredMixin, View):

    def get(self, request, *args, **kwargs):
        #waiting_match=Match.objects.filter(status='Waiting For Match')
        #if not waiting_match.exists():
        matches=Match.objects.filter(status='Waiting For Match').filter(payer=request.user)
        if matches.exists():
            messages.warning(request, 'Please complete your pending Matches')
            return HttpResponseRedirect('/office/')
        match=Match(payer=request.user)
        match.bitcoin_value=get_bitcoin_value()
        match.plan=Plan.objects.get(id=1)

        match.save()

        messages.success(request, 'Match Request Created')
        #else:
        #    messages.warning(request, 'Complete your Match request')
        return HttpResponseRedirect('/office/')

class ProfileUpdateView(LoginRequiredMixin, View):
    login_url = 'account/login'

    def get(self, request, *args, **kwargs):
        userform = UserForm(instance=self.request.user)
        profile = Profile.objects.get(user=self.request.user)
        profileform = ProfileForm(instance=profile)
        context = {'user': request.user, 'userform': userform, 'profileform': profileform}
        return render(self.request, 'remiel_admin/profile.html', context)

    def post(self, request, *args, **kwargs):
        try:
            userform = UserForm(data=self.request.POST, instance=self.request.user)
            profile = Profile.objects.get(user=self.request.user)
            profileform = ProfileForm(data=self.request.POST, instance=profile, files=request.FILES)
            userform.save()
            profileform.save()
            messages.success(request, 'Profile Updated Successfully')
        except:
            messages.warning(request, 'Invalid form input, please try again or send email to hello@dailynaija.com')

        return HttpResponseRedirect('/office/profile')


class MatchAdmin(LoginRequiredMixin, View):

    def get(self, request, *args, **kwargs):
        if request.user.is_staff == True:
            inv=Investment(plan_id=1,owner=request.user,status='Complete')
            inv.save()
            inv.mature_inv()
            messages.success(request, 'Payment Request Created, Wait for the next match ')
        return HttpResponseRedirect('/office/')


def make_match():
    pays=Payment.objects.exclude(status='Completed').order_by('created_date')
    matches=Match.objects.filter(status='Waiting For Match').order_by('created_date')
    index=0
    for pay in pays:
        try:
            match=matches[index]
        except IndexError:
            break
        if pay.investment.owner != match.receiver:
            match.complete_match(pay.investment, pay)
        index+=1
        pay.match()






def chk_investment():
    invs=Investment.objects.filter(status='Maturing')
    for inv in invs:
        now=timezone.now()
        if inv.maturity_date < now:
            inv.mature_inv()

dashboard/templates/remiel_admin/evidences.html
                                                <div role="tabpanel" class="tab-pane" id="gallery">
                                                    <div class="row">
                                                        {% for evidence in evidences %}
                                                        <div class="col-md-3 col-sm-6">
                                                            <a class="gallery-box" href="{{evidence.proof.url}}" data-lightbox="gallery">
                                                                <img src="{{evidence.proof.url}}" alt="" class="img-responsive">
                                                                <div class="gallery-overlay">
                                                                    <i class="ion-ios-eye-outline"></i>
                                                                </div>
                                                            </a>
                                                            {% empty %}

                                                        </div>
                                                        <p>No Evidence Of Payment Yet</p>

                                                        {% endfor %}



                                                    </div>



                                                </div>

dashboard/templates/remiel_admin/fileupload.html
{% extends 'remiel_admin/base.html' %}
{% load static %}
{% block content %}

 <div class="container">

                        <div class="row">
                            <div class="col-sm-12">
                                <div class="panel">
                                    <header class="panel-heading">
                                        <div class="panel-actions">
                                            <a href="#" class="panel-action panel-action-toggle" data-panel-toggle=""></a>
                                            <a href="#" class="panel-action panel-action-dismiss" data-panel-dismiss=""></a>
                                        </div>
                                        <h2 class="panel-title">Upload Evident <span class="helping-text">Drag & drop file upload</span></h2>

                                    </header>
                                    <div class="panel-body">
                                        <form id="my-awesome-dropzone"   action="{% url 'dash:upload_evidence' match.pk %}" class="dropzone">
                                            {% csrf_token %}
                                            <a href="{% url 'dash:match' %}" class="btn btn-primary rounded pull-right">Back</a>
                                        </form>
                                    </div>
                                </div>
                            </div>


                        </div>
                    </div>
 {% endblock %}

{% block scripts %}

<!-- DROPZONE -->
        <script src="{% static 'assets/plugins/dropzone/dropzone.js'  %} "></script>
        <script>

        </script>
{% endblock %}

dashboard/templates/remiel_admin/match.html
{% extends 'remiel_admin/base.html' %}
{% block content %}

                <!--start main content-->

                    <div class="container">
                    	 {% if messages %}
                {% for message in messages %}
                <div class="alert alert-{{message.tags}} alert-dismissable">
                  <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                  <strong>{{message}}</strong>
                </div>
                {%endfor%}
              {% endif %}


                       {% if request.user.is_staff %}
                        <div class="row">
                            <div class="col-md-12">
                                     <div class="panel">
                                    <header class="panel-heading">
                                        <h2 class="panel-title">Admin Functions</h2>
                                    </header>
                                         <div class="panel-body">
                                             <div class="row">
                                                 <div class="col-md-4">
                                                     <a href="/office/matchadmin" class="btn btn-info">Match Me</a>
                                                 </div>
                                             </div>
                                         </div>
                                     </div>
                            </div>
                        </div>
                        {% endif %}




                            <div class="row">
                                <div class="col-md-12">
                                     <div class="panel">
                                    <header class="panel-heading">
                                        <h2 class="panel-title">Receive Matches</h2>
                                    </header>
                                    <div class="panel-body">
                                      <div class="table-responsive">
                                <table class="table table-hover">
                                    <thead>
                                        <tr>
                                            <th>from</th>
                                            <th>Amount</th>
                                            <th>Bitcoin Value</th>
                                            <th>Status</th>
                                            <th>Proof</th>
                                            <th>Expiry Date</th>
                                            <th>Action</th>

                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for match in arm %}
											<tr>

                                              <td><a data-url="{% url 'dash:ajax_user' match.payer.pk%}" class="js_modal" href="#">{{match.payer.username}}</a></td>
											  <td>{{match.plan.amount}}</td>
											  <td>{{match.bitcoin_value|floatformat:8}}</td>
											  <td>{{match.status}}</td>
                                               {% if match.evidence_set.all %}<td ><a href="#" data-url="{% url 'dash:ajax_evidence'%}?match_id={{match.pk}}"  class="js_modal" match_id="{{match.id}}">View Evidence of payment</a></td>{% else %} <td>No proof of payment yet</td>{% endif %}
											  <td>{{match.expiry_date}}</td>
                                                <td>{% if match.evidence_set.all %}<button data-toggle="modal" data-target="#confirmmodal" data-url="{% url 'dash:ajax_action' %}?match_id={{match.pk}}&action=Complete"  class="js_action btn btn-primary" id="accept_apyment"  >Accept Payment</button>{% else %} No  payment yet{% endif %}
                                                 {% if match.grace %}<button data-toggle="modal" data-target="#confirmmodal" data-url="{% url 'dash:ajax_action' %}?match_id={{match.pk}}&action=Extend"  class="js_action btn btn-warning"  >Extend Payment</button>{% endif %}
                                                </td>
                                            </tr>
											{% endfor %}
                                    </tbody>
                                   </table>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>

                 <hr>
                  <div class="row">
                                <div class="col-md-12">
                                     <div class="panel">
                                    <header class="panel-heading">
                                        <h2 class="panel-title">Pay Order</h2>
                                        <a href="{% url 'dash:request_match'%}" class="btn btn-success pull-right">Request For Match </a>
                                    </header>
                                    <div class="panel-body">
                                      <div class="table-responsive">
                                <table class="table table-hover">
                                    <thead>
                                        <tr>
                                            <th>To</th>
                                            <th>Amount</th>
                                            <th>Bitcoin Value</th>
                                            <th>Status</th>
                                            <th>Proof</th>
                                            <th>Expiry Date</th>
                                            <th>Action</th>

                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for match in apm %}
											<tr>

                                             {% if match.status == 'Waiting For Match' %}<td>No match Yet</td>{% else %}  <td><a data-url="{% url 'dash:ajax_user' match.receiver.pk%}" class="js_modal" href="#">{{match.receiver.username}}</a></td>{% endif %}
											  <td>{{match.plan.amount}}</td>
											  <td>{{match.bitcoin_value|floatformat:8}}</td>
											  <td>{{match.status}}</td>
                                                <td ><a href="#" data-url="{% url 'dash:ajax_evidence'%}?match_id={{match.pk}}"  class="js_modal" match_id="{{match.id}}">View Evidence of payment</a></td>
											  <td>{{match.expiry_date}}</td>
                                               {% if match.status == 'Waiting For Match' %}<td>No match Yet</td>{% else %}  <td><a  class=" btn btn-primary"  href="{% url 'dash:upload_evidence' match.pk %}">Upload Evident</a>{% endif %}

                                                </td>
                                            </tr>
											{% endfor %}
                                    </tbody>
                                   </table>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>

                <div class="row">
                                <div class="col-md-12">
                                     <div class="panel">
                                    <header class="panel-heading">
                                        <h2 class="panel-title">Active Investment</h2>
                                    </header>
                                    <div class="panel-body">
                                      <div class="table-responsive">
                                <table class="table table-hover">
                                    <thead>
                                        <tr>

                                            <th>Amount ($)</th>

                                            <th>Status</th>
                                            <th>Date Added</th>


                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for inv in ainv %}
											<tr>

                                              <td>{{inv.plan.amount}}</td>
											  <td>{{inv.status}}</td>
                                              <td>{{inv.maturity_date}}</td>


                                            </tr>
											{% endfor %}
                                    </tbody>
                                   </table>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>










                        </div>











        <div id="datamodal" class="modal fade" role="dialog">

               <div class="modal-dialog">

                <!-- Modal content-->
                <div class="modal-content">

                </div>

               </div>
             </div>
	    </div>

        <div id="confirmmodal" class="modal fade" role="dialog">

               <div class="modal-dialog">

                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <h4>Confirm Payment </h4>
                    </div>
                    <div class="modal-body">
                        <p>Are you sure you want to <span class="js-action-text"></span> ?</p>
                    </div>
                    <div class="modal-footer">
                        <button class="js-action-button" data-url="">Accept</button>
                    </div>

                </div>

               </div>
             </div>
	    </div>


                    {% endblock %}

                    {% block scripts %}
	<script>


$('.js_action').click(function(){
    match_id=$(this).attr('match_id');
    url=$(this).attr('data-url');
   $('.js-action-button').attr('data-url', url)
    $('.js-action-button').text($(this).text());
   $('.js-action-text').text($(this).text());

  })

$('.js-action-button').click(function(){
    url=$(this).attr('data-url');
    $.get(url, function(){})
        .done( function(data){
            console.log('shit')
            window.location=data.redirect_url;
        })
})

var loadContent = function () {
    var btn = $(this);
    $.ajax({
        url: btn.attr("data-url"),
        type: 'get',
        dataType: 'json',
        beforeSend: function () {
            $("#datamodal").modal("show");
        },
        success: function (data) {
            console.log(data);
            $("#datamodal .modal-content").html(data.html_data);

        }
    });

};
$(".js_modal").click(loadContent);
</script>
{% endblock %}

dashboard/templates/remiel_admin/profile.html
{% extends 'remiel_admin/base.html' %}
{% block content %}
                    <div class="container">
                     
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="panel">
                                    <header class="panel-heading">
                                     
                                        <h2 class="panel-title">Edit Profile</h2>
                                   </header>
                                    <div class="panel-body">
                                        <form method="post" role="form">
                                             {%csrf_token %}
                                            <div class="form-group">
                                                <label>First Name</label>  
                                                {{userform.first_name}}
                                            </div>
                                            <div class="form-group">
                                                <label>Last Name</label>  
                                                {{userform.last_name}}
                                            </div>

                                            <div class="form-group">
                                                <label>Email</label>  
                                                {{userform.email}}
                                            </div>
                                            <div class="form-group">
                                                <label>Username</label>  
                                                {{userform.username}}
                                            </div>
                                            <div class="form-group">
                                                <label>Mobile No</label>  
                                                {{profileform.phone}}
                                            </div>
                                            
                                            <div class="form-group">
                                                <label>Profile Picture</label>
                                               {{profileform.picture}}
                                            </div>

                                            <div class="form-group">
                                                <label>Bitcoin Address</label>
                                                {{profileform.bit_address}}
                                            </div>

                                            <div class="pull-right">
                                                <button type="submit" class="btn btn-success rounded">Save</button>
                                            </div>



                                            
                                        </form>    
                                    </div>
                                </div>
                            </div>
                             
                             
                        </div>
                    </div>

                    <!--footer start-->
                    {% endblock %}

dashboard/templates/remiel_admin/user_info.html
<div class="panel">
     <div class="panel-body">
                                        <div class="profile-info">
                                            <img src="{{user.profile.picture.url}}" alt="" width="120" class="img-circle">
                                            <h4>{{user.first_name}} {{user.last_name}}</h4>
                                            <p class="text-uppercase color-info">{{user.email}}</p>
                                            <h4>Phone:</h4><p class="text-uppercase color-info"> {{user.profile.phone}}</p>
                                            <h4>Bitcoin Address:</h4><p class="text-uppercase color-info"> {{user.profile.bit_address}}</p>

                                            <div class="space-30"></div>

                                        </div><!--profile info-->
                                    </div><!--panel body-->
                                </div><!--panel-->